---
- name: Ansible Playbook for testing coolstore EDA
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: Debug details
      ansible.builtin.debug:
        var: ansible_eda.event.payload.name

    - name: Debug details 2
      ansible.builtin.debug:
        var: ansible_eda.event.payload.updated_tags[0]
