---
- name: Login to quay.io and create ${XDG_RUNTIME_DIR}/containers/auth.json
  containers.podman.podman_login:
    username: "{{ quay_user }}"
    password: "{{ quay_password }}"
    registry: "{{ quay_registry }}"

- name: Remove containers if already exist
  containers.podman.podman_container:
    name: "{{ item }}"
    state: absent
  loop:
    - Inventory
    - Springboot
    - Vertx
    - Web
    
- name: Force pull images
  containers.podman.podman_image:
    name: "{{ item }}"
    force: true
  loop:
    - "{{ inventory_image }}"
    - "{{ springboot_image }}"
    - "{{ vertx_image }}"
    - "{{ web_image }}"

- name: Create inventory container
  containers.podman.podman_container:
    name: "Inventory"
    image: "{{ inventory_image }}"
    state: started
    recreate: true
    ports:
      - "8080:8080"

- name: Create springboot container
  containers.podman.podman_container:
    name: "Springboot"
    image: "{{ springboot_image }}"
    state: started
    recreate: true
    ports:
      - "9000:8080"

- name: Create vertx container
  containers.podman.podman_container:
    name: "Vertx"
    image: "{{ vertx_image }}"
    state: started
    recreate: true
    ports:
      - "8090:8080"
    env:
      COMPONENT_CATALOG_HOST: "{{ container_address }}"
      COMPONENT_CATALOG_PORT: "9000"
      COMPONENT_INVENTORY_HOST: "{{ container_address }}"
      COMPONENT_INVENTORY_PORT: "8080"

- name: Create web container
  containers.podman.podman_container:
    name: "Web"
    image: "{{ web_image }}"
    state: started
    recreate: true
    ports:
      - "80:8080"
    env:
      COOLSTORE_GW_ENDPOINT="http://{{ container_address}}:8090"
