---
- name: Capture Events from source
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Capture all other events from this source
      condition: event.payload.updated_tags is not select("search","sha256")
      action:
        run_workflow_template:
          name: 'Coolstuff store edge deployment'
          organization: Default
