- name: Launch an AWS EC2 instance
  amazon.aws.ec2_instance:
    name: "{{ my_name }}"
    key_name: "{{ key }}"
    wait: yes
    state: running
    instance_type: "{{ instance_type }}"
    image_id: "{{ image_id }}"
    region: "{{ region }}"
    security_group: "{{ security_group }}"
    wait: yes
    volumes:
    - device_name: "{{ device_name }}"
      ebs:
        volume_type: "{{ volume_type }}"
        volume_size: "{{ volume_size }}"
    tags:
      Name: "{{ my_name }}"
      owner: "{{ owner }}"
      sleep_schedule: "{{ sleep_schedule }}"
    vpc_subnet_id: "{{ subnet_id }}"
    network:
      assign_public_ip: yes

- name: Gather info about instance
  amazon.aws.ec2_instance_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ my_name }}"
      instance-state-name: running
  register: ec2_node_info

- name: flatten object
  ansible.builtin.set_fact:
    paths: "{{ lookup('ansible.utils.to_paths', ec2_node_info) }}"

- name: Wait for SSH to respond
  ansible.builtin.wait_for:
    host: "{{ paths['instances[0].public_ip_address'] }}"
    port: 22
    state: started
